export * from './platform/SuperAdmin';
export * from './platform/Tenant';
export * from './master/InsuranceCompany';
export * from './master/PolicyType';
export * from './master/RTO';
export * from './master/VehicleType';
export * from './users/User';
export * from './core/Customer';
export * from './core/Policy';
